name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build, run_release]

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [[macos-latest, bash], [ubuntu-latest, bash], [windows-latest, msys2]]
    defaults:
     run:
      shell: ${{ matrix.os[1] }} {0}

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Ubuntu texinfo bison flex
      if: matrix.os[0] == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install texinfo bison flex gettext
    
    - name: Install Mac texinfo bison flex
      if: matrix.os[0] == 'macOS-latest'
      run: |
        brew update
        brew install texinfo bison flex gettext

    - name: Install MSYS2 texinfo bison flex
      if: matrix.os[0] == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: base-devel git make texinfo flex bison patch binutils mingw-w64-i686-gcc
        update: true
        shell: msys2 {0}

    - name: Runs all the stages in the shell
      run: |
        export PS2DEV=$PWD/ps2dev
        export PATH=$PATH:$PS2DEV/iop/bin
        ./toolchain.sh
    
    - name: Print bins version
      run: |
        export PS2DEV=$PWD/ps2dev
        export PATH=$PATH:$PS2DEV/iop/bin
        iop-as --version
        iop-ld --version
        iop-gcc --version
